# Generated by Django 5.1.6 on 2025-04-07 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentByMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('INDV', 'Individual'), ('RES', 'Residential'), ('EDU', 'Education'), ('FIS', 'Financial Institution'), ('REG', 'Religious'), ('BUS', 'Business/Manufacturing'), ('GOV', 'Government Agencies')], max_length=5, unique=True)),
                ('rate', models.FloatField()),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
        migrations.CreateModel(
            name='RevenueTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('target', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TopPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UnpaidBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AccumulatedOwing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accumulated_owings', to='accounts.datacapture')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_year', models.PositiveIntegerField()),
                ('brought_forward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name_mmda', models.CharField(max_length=255)),
                ('ghana_card', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('gps_address', models.CharField(max_length=255)),
                ('bill_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rooms', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partly_paid', 'Partly Paid'), ('paid', 'Paid')], default='unpaid', max_length=15)),
                ('payment_option', models.CharField(choices=[('full', 'Full'), ('installments', 'Installments')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='accounts.datacapture')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mmda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='accounts.mmda')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='billing.billing')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('bill', 'Bill'), ('payment', 'Payment')], max_length=10)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('cr_account_name', models.CharField(max_length=255)),
                ('year_bill', models.PositiveIntegerField()),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=50)),
                ('cr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='accounts.mmda')),
                ('dr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='accounts.datacapture')),
            ],
            options={
                'verbose_name': 'Customer Statement',
                'verbose_name_plural': 'Customer Statements',
                'ordering': ['-date_generated'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=50)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.billing')),
            ],
        ),
    ]
