# Generated by Django 5.1.6 on 2025-04-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='dr_account',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
