# Generated by Django 5.1.6 on 2025-04-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_ghmedicalfacility_delete_ghis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghmedicalfacility',
            name='Accessibility_of_facility',
            field=models.CharField(choices=[('Difficult', 'Difficult'), ('Easy', 'Easy'), ('Encouraged', 'Encouraged')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('GPS', 'Ghana Police Service (GPS)'), ('PS', 'Prisons Service (PS)'), ('GNFS', 'Ghana National Fire Service(GNFS) )'), ('GIS', 'Ghana Immigration Service (GIS)'), ('GHS', 'Ghana Health Service (GHS)'), ('GMF', 'Ghana Medical Facility (GMF)')], max_length=255, unique=True),
        ),
    ]
