# Generated by Django 5.1.6 on 2025-04-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_ghmedicalfacility_accessibility_of_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghmedicalfacility',
            name='type_facility',
            field=models.CharField(choices=[('Chip Compound', 'Chip Compound'), ('Clinic', 'Clinic'), ('Hospital', 'Hospital'), ('Maternity Home', 'Maternity Home'), ('Pharmarcy', 'Pharmarcy'), ('other', 'other')], max_length=30),
        ),
    ]
