# Generated by Django 5.1.6 on 2025-04-12 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_deliveryreport_signalmessage_deliveryreport_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalmessage',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='signalmessage',
            name='divisions',
        ),
        migrations.RemoveField(
            model_name='signalmessage',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='signalmessage',
            name='stations',
        ),
        migrations.AddField(
            model_name='signalmessage',
            name='districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.district'),
        ),
        migrations.AddField(
            model_name='signalmessage',
            name='divisions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.division'),
        ),
        migrations.AddField(
            model_name='signalmessage',
            name='regions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.policeregion'),
        ),
        migrations.AddField(
            model_name='signalmessage',
            name='stations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.policestation'),
        ),
    ]
