# Generated by Django 5.1.6 on 2025-04-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_signalmessage_districts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalmessage',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='signalmessage',
            name='divisions',
        ),
        migrations.RemoveField(
            model_name='signalmessage',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='signalmessage',
            name='stations',
        ),
        migrations.AddField(
            model_name='signalmessage',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.district'),
        ),
        migrations.AddField(
            model_name='signalmessage',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.division'),
        ),
        migrations.AddField(
            model_name='signalmessage',
            name='police_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.policeregion'),
        ),
        migrations.AddField(
            model_name='signalmessage',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.policestation'),
        ),
        migrations.AlterField(
            model_name='signalmessage',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High Classified'), ('MODERITY', 'Moderate'), ('NORMAL', 'Normal')], default='NORMAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='signalmessage',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read')], default='DRAFT', max_length=30),
        ),
    ]
