# Generated by Django 5.1.6 on 2025-04-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_signalmessage_districts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghanafirestation',
            name='avilability_of_hydrants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ghanafirestation',
            name='no_of_vehicle_firehydrant',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ghanapoliceservice',
            name='avilability_of_hydrants',
            field=models.BooleanField(default=False),
        ),
    ]
