# Generated by Django 5.1.6 on 2025-04-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_historicaldatacapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacapture',
            name='fire_extinguishers_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datacapture',
            name='fire_hydrant_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldatacapture',
            name='fire_extinguishers_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldatacapture',
            name='fire_hydrant_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='residentialcapture',
            name='building_description',
            field=models.CharField(choices=[('Paint', 'Paint'), ('Ceramic', 'Ceramic'), ('Tires', 'Tires'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='residentialcapture',
            name='land_size',
            field=models.CharField(choices=[('Half Plot', 'Half Plot'), ('Quarter Plot', 'Quarter Plot'), ('One Plot', 'One Plot'), ('2 Plot', '3 Plot'), ('3 Plot', '3 Plot'), ('One Acre or more', 'One Acre or more')], max_length=50),
        ),
    ]
