# Generated by Django 5.1.6 on 2025-04-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_datacapture_fire_extinguishers_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacapture',
            name='fire_extinguishers_availability',
        ),
        migrations.RemoveField(
            model_name='datacapture',
            name='fire_hydrant_availability',
        ),
        migrations.RemoveField(
            model_name='historicaldatacapture',
            name='fire_extinguishers_availability',
        ),
        migrations.RemoveField(
            model_name='historicaldatacapture',
            name='fire_hydrant_availability',
        ),
        migrations.AddField(
            model_name='residentialcapture',
            name='fire_extinguishers_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialcapture',
            name='fire_hydrant_availability',
            field=models.BooleanField(default=False),
        ),
    ]
