# Generated by Django 5.1.6 on 2025-04-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_datacapture_fire_extinguishers_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smecapture',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='sme_pictures/'),
        ),
    ]
