# Generated by Django 5.1.6 on 2025-04-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_smecapture_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentcapture',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='government_pictures/'),
        ),
    ]
