# Generated by Django 5.1.6 on 2025-04-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_governmentcapture_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcapture',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='school_pictures/'),
        ),
    ]
